# Generated by Django 5.1.4 on 2024-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
