# Generated by Django 5.1.4 on 2025-02-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
